In [16]:
import numpy as np
from utils.noise import make_noise
import matplotlib.pyplot as plt

In [34]:
#画像の読み込み
Q_1 = np.loadtxt("picture/picture_1.csv", delimiter = ",", dtype = int)
Q_2 = np.loadtxt("picture/picture_2.csv", delimiter = ",", dtype = int)

In [35]:
q_1 = np.array([Q_1.flatten()])
q_2 = np.array([Q_2.flatten()])

In [36]:
q_1

array([[-1, -1,  1, -1, -1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1,
         1,  1,  1, -1, -1,  1, -1,  1, -1]])

In [37]:
fig, ax = plt.subplots()
ax.imshow(Q_2, cmap="gray")

In [6]:
#重み行列の作成
W = np.dot(q_1.T,q_1) + np.dot(q_2.T,q_2)

In [7]:
#Wの対角成分をゼロに
W_diag = np.diag(W)
W_diag.flags.writeable = True
np.putmask(W_diag, W_diag > 0, 0)

In [8]:
noise = 20
thete = 0

In [9]:
#元画像にノイズを加える
q_1_noise = make_noise(q_1, noise)

In [10]:
q_1_noise

array([[-1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1,
         1, -1,  1, -1,  1, -1,  1, -1,  1]])

In [11]:
for n in range(100):
    similar = np.dot(q_1_noise[0], q_1[0]) / 25
    print(similar)
    i = np.random.randint(25)
    if np.dot(W[i], q_1_noise[0]) - thete >= 0:
        q_1_noise[0][i] = 1
    else:
        q_1_noise[0][i] = -1

0.76
0.76
0.76
0.76
0.76
0.76
0.76
0.76
0.76
0.84
0.84
0.84
0.84
0.84
0.84
0.84
0.84
0.84
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
0.92
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [12]:
q_1

array([[ 1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1,
         1, -1, -1, -1,  1, -1,  1, -1,  1]])

In [13]:
q_1_noise

array([[ 1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1,
         1, -1, -1, -1,  1, -1,  1, -1,  1]])

In [14]:
q_2_noise = make_noise(q_2, noise)

In [15]:
q_2_noise

array([[-1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,
        -1, -1, -1, -1,  1,  1, -1, -1, -1]])

In [16]:
for n in range(100):
    i = np.random.randint(25)
    if np.dot(W[i], q_2_noise[0]) - thete >= 0:
        q_2_noise[0][i] = 1
    else:
        q_2_noise[0][i] = -1

In [17]:
q_2

array([[ 1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,
        -1, -1, -1, -1,  1,  1,  1,  1, -1]])

In [18]:
q_2_noise

array([[ 1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,
        -1, -1, -1, -1,  1,  1,  1,  1, -1]])